
'use client';

import React, { useState, useEffect } from 'react';
import { Button, buttonVariants } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardContent, CardDescription, CardFooter } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Sparkles, Search, ArrowRight, Rss, Users2, Building, Mail, LayoutGrid, Lightbulb, Bot, Settings, BriefcaseBusiness, LibraryBig, Loader2, Clock, Zap, MessageSquareText, Feather, Database, Workflow, User } from 'lucide-react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/hooks/useAuth';
import { PageHeader } from '@/components/ui/page-header';
import { tools, AiIcon } from '@/lib/tools-client';
import { Badge } from '@/components/ui/badge';

// Mock Data for Feeds
const mockAiActivity = [
    { id: 'act1', type: 'Flow Run', description: '"Listing Syndication Flow" completed for Palm Jumeirah project.', timestamp: '2 min ago', href: '/me/flows' },
    { id: 'act2', type: 'AI Content Generated', description: 'New social media captions generated by "AI Marketing Copilot".', timestamp: '1 hour ago', href: '/me/tool/ai-marketing-copilot' },
    { id: 'act3', type: 'Data Ingested', description: '5 new market reports uploaded to "Gemini Knowledge Base".', timestamp: '3 hours ago', href: '/me/brand' },
];

const mockMarketInsights = [
    { id: 'insight1', title: 'Downtown Dubai Q2 Rentals Up', description: 'Median rental prices for 1BR apartments in Downtown Dubai increased by 7% in Q2.', href: '/discover/search?q=downtown+dubai+q2+rentals' },
    { id: 'insight2', title: 'Off-Plan Launches Surge', description: 'New off-plan project launches in Arabian Ranches 3 show high investor interest.', href: '/discover/search?q=arabian+ranches+3+off-plan' },
    { id: 'insight3', title: 'Luxury Villa Demand Peak', description: 'Demand for luxury villas in Emirates Hills hit a 5-year high this month.', href: '/discover/search?q=emirates+hills+luxury+villas' },
];

const mockRecommendedTools = tools.filter(tool => ['ai-marketing-copilot', 'flow-automation-studio', 'deal-analyzer-ai'].includes(tool.id));

const mockCommunityHighlights = [
    { id: 'comm1', author: 'Agent Smith', content: 'Great tip on using AI for contract review! Saved me hours.', href: '/me/community' },
    { id: 'comm2', author: 'Developer Jane', content: 'Shared my success strategy for Q3 project launch using AI flows.', href: '/me/community' },
];

export default function MeLandingPage() {
    const { user, loading } = useAuth();
    const router = useRouter();

    useEffect(() => {
        if (!loading && !user) {
            router.replace('/login?redirect=/me');
        }
    }, [user, loading, router]);
    
    if (loading) {
        return (
             <div className="p-4 md:p-8 space-y-12 flex items-center justify-center h-screen">
                <Loader2 className="h-16 w-16 animate-spin text-primary" />
             </div>
        );
    }

    if (!user) {
        return null;
    }

    return (
        <div className="flex flex-col min-h-screen">
            <main className="flex-1 w-full max-w-7xl mx-auto px-4 md:px-6 py-12 md:py-8 space-y-20">
                <PageHeader
                    title={`Welcome back, ${user.displayName || user.email?.split('@')[0]}!`}
                    description="Your AI-powered real estate hub. Get quick insights, manage your tools, and stay connected."
                    icon={<Sparkles className="h-8 w-8 text-primary" />}
                />

                <section className="grid grid-cols-1 lg:grid-cols-3 gap-8 mt-8">
                    {/* Main Gemini Insight Card */}
                    <Card className="col-span-full lg:col-span-1 bg-gradient-to-br from-primary/10 to-accent/10 border-primary/20 shadow-xl">
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium flex items-center gap-2">
                                <Bot className="h-4 w-4 text-primary" /> Gemini Insight
                            </CardTitle>
                            <Lightbulb className="h-4 w-4 text-muted-foreground" />
                        </CardHeader>
                        <CardContent className="p-6">
                            <div className="text-2xl font-bold">"Market sentiment for Downtown Dubai is trending positive this week."</div>
                            <p className="text-xs text-muted-foreground">+5% in queries for luxury apartments.</p>
                            <Link href="/discover/search?q=downtown+dubai+market+sentiment" className="text-sm text-primary hover:underline mt-4 block"> 
                                Explore further <ArrowRight className="ml-1 inline-block h-3 w-3" />
                            </Link>
                        </CardContent>
                    </Card>

                    {/* Quick Links / Navigation Cards */}
                    <Card className="hover:shadow-lg transition-shadow duration-200 cursor-pointer h-full">
                        <Link href="/me/marketplace" className="h-full block p-6">
                            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 px-0 pt-0">
                                <CardTitle className="text-sm font-medium">My Apps</CardTitle>
                                <LayoutGrid className="h-4 w-4 text-muted-foreground" />
                            </CardHeader>
                            <CardContent className="p-0">
                                <div className="text-2xl font-bold">40+</div>
                                <p className="text-xs text-muted-foreground">AI tools at your command</p>
                            </CardContent>
                        </Link>
                    </Card>

                    <Card className="hover:shadow-lg transition-shadow duration-200 cursor-pointer h-full">
                        <Link href="/me/flows" className="h-full block p-6">
                            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 px-0 pt-0">
                                <CardTitle className="text-sm font-medium">My Flows</CardTitle>
                                <Rss className="h-4 w-4 text-muted-foreground" />
                            </CardHeader>
                            <CardContent className="p-0">
                                <div className="text-2xl font-bold">5 Active</div>
                                <p className="text-xs text-muted-foreground">Automated workflows running</p>
                            </CardContent>
                        </Link>
                    </Card>
                </section>
                
                {/* New: Your AI Activity Feed - TIMELINE VIEW */}
                <section>
                    <h2 className="text-2xl md:text-3xl font-bold font-heading mb-6 flex items-center gap-3">
                        <Clock className="h-7 w-7 text-primary" /> Your AI Activity Feed
                    </h2>
                    <div className="relative pl-6">
                        <div className="absolute left-6 top-0 bottom-0 w-0.5 bg-border -translate-x-1/2"></div>
                        <ul className="space-y-8">
                            {mockAiActivity.map(activity => (
                                <li key={activity.id} className="relative">
                                    <div className="absolute -left-6 top-1.5 w-3 h-3 bg-primary rounded-full ring-4 ring-background -translate-x-1/2"></div>
                                    <div className="ml-4">
                                        <div className="flex items-center gap-2 mb-1">
                                            {activity.type === 'Flow Run' ? <Workflow className="h-5 w-5 text-muted-foreground" /> : activity.type === 'AI Content Generated' ? <Feather className="h-5 w-5 text-muted-foreground" /> : <Database className="h-5 w-5 text-muted-foreground" />}
                                            <Badge variant="secondary">{activity.type}</Badge>
                                        </div>
                                        <Link href={activity.href} className="hover:underline">
                                            <p className="font-semibold text-foreground/90">{activity.description}</p>
                                        </Link>
                                        <p className="text-xs text-muted-foreground mt-1">{activity.timestamp}</p>
                                    </div>
                                </li>
                            ))}
                        </ul>
                    </div>
                     <div className="mt-8 text-center">
                        <Link href="/me/activity">
                            <Button variant="outline">View All AI Activity <ArrowRight className="ml-2 h-4 w-4" /></Button>
                        </Link>
                    </div>
                </section>

                {/* New: Latest Market Insights */}
                <section>
                    <h2 className="text-2xl md:text-3xl font-bold font-heading mb-6 flex items-center gap-3">
                        <Lightbulb className="h-7 w-7 text-accent" /> Latest Market Insights
                    </h2>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {mockMarketInsights.map(insight => (
                            <Card key={insight.id} className="hover:shadow-md transition-shadow duration-200 bg-muted/30">
                                <Link href={insight.href} className="block p-4">
                                    <CardTitle className="text-lg mb-1">{insight.title}</CardTitle>
                                    <CardDescription className="text-muted-foreground line-clamp-2">{insight.description}</CardDescription>
                                    <span className="text-sm text-primary hover:underline mt-2 block">Read more <ArrowRight className="ml-1 inline-block h-3 w-3" /></span>
                                </Link>
                            </Card>
                        ))}
                        <div className="md:col-span-2 text-center">
                            <Link href="/me/market-intelligence">
                                <Button variant="outline">Explore All Insights <ArrowRight className="ml-2 h-4 w-4" /></Button>
                            </Link>
                        </div>
                    </div>
                </section>

                {/* New: Recommended AI Tools & Flows */}
                <section>
                    <h2 className="text-2xl md:text-3xl font-bold font-heading mb-6 flex items-center gap-3">
                        <Bot className="h-7 w-7 text-primary" /> Recommended AI Tools & Flows
                    </h2>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                        {mockRecommendedTools.map(tool => (
                            <Link href={tool.href} key={tool.id} className="h-full block">
                                <Card className="hover:shadow-lg transition-shadow duration-200 h-full bg-card/80 backdrop-blur-sm border-border/30 flex flex-col">
                                    <CardHeader className="flex flex-col items-center text-center p-4 pb-2">
                                        <div className="p-3 rounded-full text-white mb-3" style={{ backgroundColor: tool.color || 'hsl(var(--primary))' }}>
                                            {React.cloneElement(tool.icon as React.ReactElement, { className: 'h-6 w-6' })}
                                        </div>
                                        <CardTitle className="text-lg font-semibold">{tool.dashboardTitle || tool.title}</CardTitle>
                                    </CardHeader>
                                    <CardContent className="text-center p-4 pt-2 flex-grow">
                                        <CardDescription className="text-muted-foreground line-clamp-3">
                                            {tool.description}
                                        </CardDescription>
                                    </CardContent>
                                    <CardFooter className="p-4 pt-0 text-center">
                                        <div className={buttonVariants({ variant: 'outline', className: 'w-full' })}>Learn More</div>
                                    </CardFooter>
                                </Card>
                            </Link>
                        ))}
                        <div className="lg:col-span-3 text-center">
                            <Link href="/me/marketplace">
                                <Button variant="outline">Explore All AI Apps <ArrowRight className="ml-2 h-4 w-4" /></Button>
                            </Link>
                        </div>
                    </div>
                </section>

                 {/* New: Community Highlights */}
                <section>
                    <h2 className="text-2xl md:text-3xl font-bold font-heading mb-6 flex items-center gap-3">
                        <MessageSquareText className="h-7 w-7 text-secondary" /> Community Highlights
                    </h2>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {mockCommunityHighlights.map(highlight => (
                            <Card key={highlight.id} className="hover:shadow-md transition-shadow duration-200 cursor-pointer bg-muted/30">
                                <Link href={highlight.href} className="block p-4">
                                    <CardTitle className="text-md mb-1">{highlight.content}</CardTitle>
                                    <CardDescription className="text-xs text-muted-foreground flex items-center gap-1 mt-1">
                                        <User className="h-3 w-3" /> {highlight.author}
                                    </CardDescription>
                                </Link>
                            </Card>
                        ))}
                        <div className="md:col-span-2 text-center">
                            <Link href="/me/community">
                                <Button variant="outline">View All Community Insights <ArrowRight className="ml-2 h-4 w-4" /></Button>
                            </Link>
                        </div>
                    </div>
                </section>

            </main>
        </div>
    );
}
